# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - backup_migration_*/
    - DEEPSEEK_V3_REPLACEMENT_COMPLETE/**
    - "مجلد جديد/**"
    - New folder/**
    - venv/**
  errors:
    todo: ignore  # Ignore TODO comments

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    # Disable non-critical lints for production app
    avoid_print: false  # We use print for logging in production
    prefer_const_constructors: false  # Not critical for functionality
    prefer_const_declarations: false  # Not critical for functionality
    prefer_const_literals_to_create_immutables: false  # Not critical
    curly_braces_in_flow_control_structures: false  # Style preference
    dangling_library_doc_comments: false  # Documentation style
    prefer_const_constructors_in_immutables: false  # Not critical
    constant_identifier_names: false  # Naming convention
    use_super_parameters: false  # Modern Dart feature, not critical
    unnecessary_brace_in_string_interps: false  # Style preference
    sized_box_for_whitespace: false  # Performance hint, not critical
    prefer_final_fields: false  # Code style
    prefer_is_empty: false  # Style preference
    unnecessary_string_interpolations: false  # Style preference
    unnecessary_to_list_in_spreads: false  # Style preference
    no_leading_underscores_for_local_identifiers: false  # Naming convention
    non_constant_identifier_names: false  # Naming convention
    use_build_context_synchronously: false  # We check mounted, safe to ignore
    library_private_types_in_public_api: false  # Internal state classes
    depend_on_referenced_packages: false  # Transitive dependencies are OK

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
